apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2  # Adjust as needed
  selector:
    matchLabels:
      app: app-container
  template:
    metadata:
      labels:
        app: app-container
    spec:
      containers:
        - name: app-container
          image: gcr.io/tokopedia-auction/be-tokopedia-auction:latest  # Update with your GCR detail
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
        - name: postgres-container
          image: gcr.io/tokopedia-auction/postgres:latest  # Update with your GCR details
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_DB
              value: "tokopedia-auction"
          volumeMounts:
            - name: pgdata-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: logs-volume
          emptyDir: {}
        - name: pgdata-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
