apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: gcr.io/tokopedia-auction/be-tokopedia-auction:latest  # Update with your GCR details
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: logs-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
