name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: "latest"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Check Docker Version
        run: docker --version

      - name: Check gcloud Version
        run: gcloud version

      - name: Install Google Cloud SDK
        run: |
          wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
          tar -xzf google-cloud-sdk.tar.gz
          ./google-cloud-sdk/install.sh

      - name: Configure Docker and Authenticate with GCR
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcp-key.json
          gcloud auth activate-service-account 998596668254-compute@developer.gserviceaccount.com --key-file=${HOME}/gcp-key.json --project=${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker
        env:
          PATH: ${{ github.workspace }}/google-cloud-sdk/bin:$PATH

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to GCP
        run: |
          gcloud run deploy tokped-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/tokped-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
