name: Deploy to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-southeast1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: tokopedia-auction-cluster # TODO: update to cluster name
  GKE_ZONE: asia-southeast1-b # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  REPOSITORY: tokopedia-auction # TODO: update to Artifact Registry docker repository
  IMAGE: be-tokopedia-auction

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure Workload Identity Federation and generate an access token.
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Install dependencies
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud components update

      # Push the Docker image to Google Artifact Registry
      - name: Build and push application image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE }}:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE }}:latest

      # Deploy the Docker image to the GKE cluster
      # Note: Images should set to public
      # TODO: Set credential to kubectl, so image can be pull in private
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
          kubectl get namespaces
          kubectl config current-context

      - name: Deploy to GKE
        run: |
          kubectl apply -f postgres-config.yaml 
          kubectl apply -f postgres-pvc-pv.yaml 
          kubectl apply -f postgres-deployment.yaml 
          kubectl apply -f postgres-service.yaml 
          kubectl apply -f kubernetes-deployment.yaml
          kubectl get services -o wide
